### ISSUE TITLE
External javascript

### ISSUE THREAD

**Issue by SiddharthaMishra-dev** [sahaavi/Form-Validation-JavaScript#1]
Can create separate js files for javascript rather than embedding them in the same HTML file. It increases modularity of the project.
@sahaavi

**Comment by sahaavi** [comment]
Thank you. Please feel free to proceed with the suggested changes and submit a pull request if you would like to.

**Comment by SiddharthaMishra-dev** [comment]
I have done the changes and created the pull request.

**Comment by sahaavi** [comment]
Reviewed and merged @SiddharthaMishra-dev ! Thanks for the contribution.
